/* Generated By:JJTree: Do not edit this line. Atribuicao.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.compilador.analisador;

public
class Atribuicao extends CustomNode {
  public Atribuicao(int id) {
    super(id);
  }

  public Atribuicao(Gramatica p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GramaticaVisitor visitor, Controlador data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f01f9bc12e7da90f61b94ceea699fa1b (do not edit this line) */
