/* Generated By:JJTree: Do not edit this line. CorpoFuncao.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.compilador.analisador;

public
class CorpoFuncao extends CustomNode {
  public CorpoFuncao(int id) {
    super(id);
  }

  public CorpoFuncao(Gramatica p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GramaticaVisitor visitor, Controlador data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f8e0683ed60beeaa3e100a554cfdc800 (do not edit this line) */
