/* Generated By:JJTree: Do not edit this line. ExpressaoLogica.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.compilador.analisador;

public
class ExpressaoLogica extends CustomNode {
  public ExpressaoLogica(int id) {
    super(id);
  }

  public ExpressaoLogica(Gramatica p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GramaticaVisitor visitor, Controlador data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=67266631667261a7891517273334a0d3 (do not edit this line) */
