/* Generated By:JJTree: Do not edit this line. Funcao.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.compilador.analisador;

public
class Funcao extends CustomNode {
  public Funcao(int id) {
    super(id);
  }

  public Funcao(Gramatica p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GramaticaVisitor visitor, Controlador data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ea10b55d1e4dfc387f477d4a345fc7c3 (do not edit this line) */
