/* Generated By:JavaCC: Do not edit this line. GramaticaVisitor.java Version 5.0 */
package br.compilador.analisador;

public interface GramaticaVisitor
{
  public Object visit(SimpleNode node, Controlador data);
  public Object visit(Programa node, Controlador data);
  public Object visit(Funcao node, Controlador data);
  public Object visit(TipoRetorno node, Controlador data);
  public Object visit(ParametroFuncao node, Controlador data);
  public Object visit(CorpoFuncao node, Controlador data);
  public Object visit(Declaracao node, Controlador data);
  public Object visit(Atribuicao node, Controlador data);
  public Object visit(ExpressaoMatematica node, Controlador data);
  public Object visit(Adicao node, Controlador data);
  public Object visit(Subtracao node, Controlador data);
  public Object visit(Multiplicacao node, Controlador data);
  public Object visit(Divisao node, Controlador data);
  public Object visit(Identificador node, Controlador data);
  public Object visit(Numero node, Controlador data);
  public Object visit(If node, Controlador data);
  public Object visit(Else node, Controlador data);
  public Object visit(While node, Controlador data);
  public Object visit(Return node, Controlador data);
  public Object visit(ExpressaoLogica node, Controlador data);
  public Object visit(Or node, Controlador data);
  public Object visit(And node, Controlador data);
  public Object visit(MenorQue node, Controlador data);
  public Object visit(MaiorQue node, Controlador data);
  public Object visit(Igual node, Controlador data);
  public Object visit(Diferente node, Controlador data);
  public Object visit(MenorIgual node, Controlador data);
  public Object visit(MaiorIgual node, Controlador data);
}
/* JavaCC - OriginalChecksum=c59380846eb31c5803e9e6c10098f7fd (do not edit this line) */
