/* Generated By:JJTree: Do not edit this line. ParametroFuncao.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.compilador.analisador;

public
class ParametroFuncao extends CustomNode {
  public ParametroFuncao(int id) {
    super(id);
  }

  public ParametroFuncao(Gramatica p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GramaticaVisitor visitor, Controlador data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8f773af2f636ebc55d903de32d46541f (do not edit this line) */
