/* Generated By:JJTree: Do not edit this line. TipoMatematico.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.compilador.analisador;

public
class TipoMatematico extends CustomNode {
  public TipoMatematico(int id) {
    super(id);
  }

  public TipoMatematico(Gramatica p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GramaticaVisitor visitor, Controlador data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=59edcc7bd2cac2560c3193ab4762fe71 (do not edit this line) */
