/* Generated By:JavaCC: Do not edit this line. GramaticaTreeConstants.java Version 5.0 */
package br.unipe.compilador.analisador;

public interface GramaticaTreeConstants
{
  public int JJTPROGRAMA = 0;
  public int JJTFUNCAO = 1;
  public int JJTTIPORETORNO = 2;
  public int JJTVOID = 3;
  public int JJTPARAMETROFUNCAO = 4;
  public int JJTCORPOFUNCAO = 5;
  public int JJTDECLARACAO = 6;
  public int JJTATRIBUICAO = 7;
  public int JJTEXPRESSAOMATEMATICA = 8;
  public int JJTADICAO = 9;
  public int JJTSUBTRACAO = 10;
  public int JJTMULTIPLICACAO = 11;
  public int JJTDIVISAO = 12;
  public int JJTIDENTIFICADOR = 13;
  public int JJTNUMERO = 14;
  public int JJTIF = 15;
  public int JJTELSE = 16;
  public int JJTWHILE = 17;
  public int JJTRETURN = 18;
  public int JJTEXPRESSAOLOGICA = 19;
  public int JJTOR = 20;
  public int JJTAND = 21;
  public int JJTMENORQUE = 22;
  public int JJTMAIORQUE = 23;
  public int JJTIGUAL = 24;
  public int JJTDIFERENTE = 25;
  public int JJTMENORIGUAL = 26;
  public int JJTMAIORIGUAL = 27;


  public String[] jjtNodeName = {
    "Programa",
    "Funcao",
    "TipoRetorno",
    "void",
    "ParametroFuncao",
    "CorpoFuncao",
    "Declaracao",
    "Atribuicao",
    "ExpressaoMatematica",
    "Adicao",
    "Subtracao",
    "Multiplicacao",
    "Divisao",
    "Identificador",
    "Numero",
    "If",
    "Else",
    "While",
    "Return",
    "ExpressaoLogica",
    "Or",
    "And",
    "MenorQue",
    "MaiorQue",
    "Igual",
    "Diferente",
    "MenorIgual",
    "MaiorIgual",
  };
}
/* JavaCC - OriginalChecksum=9db50e3a5ed1a30f9e274c638c0ec732 (do not edit this line) */
