/* Generated By:JJTree: Do not edit this line. TipoRetorno.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.unipe.compilador.analisador;

public
class TipoRetorno extends CustomNode {
  public TipoRetorno(int id) {
    super(id);
  }

  public TipoRetorno(Gramatica p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GramaticaVisitor visitor, Controlador data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=43416d14e56a8e551a4ff6a16a60d1f9 (do not edit this line) */
